### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by ravidsrk** [thyrlian/Captain-ADB#3]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by thyrlian** [comment]
Sorry, my bad.  Thanks for pointing it out.

It's now added by this [commit](https://github.com/thyrlian/Captain-ADB/commit/9eaf6a3162854066c74897c547d1c86a24b67aaf).

**Comment by ravidsrk** [comment]
Thanks
